// <auto-generated />
using System;
using GraphQL_DotNetCore.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraphQL_DotNetCore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221115083839_InitialDbMigration")]
    partial class InitialDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GraphQL_DotNetCore.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cash account for our users",
                            Type = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Savings account for our users",
                            Type = "Savings"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Income account for our users",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Expense account for our users",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("GraphQL_DotNetCore.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Chennai",
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "John@gmail.com",
                            Name = "John",
                            Phone = "9898324233"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pune",
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Smith@gmail.com",
                            Name = "Smith",
                            Phone = "9898312344"
                        });
                });

            modelBuilder.Entity("GraphQL_DotNetCore.Entities.OwnerAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OwnerAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            OwnerId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
